- name: Add the packages in sources lists
  command: apt install apt-transport-https lsb-release software-properties-common ca-certificates -y 

- name: Add php repository
  apt_repository:
   repo: 'ppa:ondrej/php'

- name: Update the apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installing Php Packages
  package:
      name: "{{ item }}"
      state: present
  with_items:
      - libapache2-mod-php
      - php
      - php-common
      - php-xml
      - php-mysql
      - php-mbstring
      - php-tokenizer
      - php-json
      - php-bcmath
      - php-zip
      - unzip
      - python3-pymysql
      - php-fpm

#- name: Configure Php
 # lineinfile: 
  #   dest: /etc/php/8.1/apache2/php.ini 
   #  regexp: '^(.*)cgi.fix_pathinfo=' 
    # line: cgi.fix_pathinfo=0
